### ISSUE TITLE
Nested Partial Disclosure breaks assumptions?

### ISSUE THREAD

**Issue by jasoncolburne** [WebOfTrust/ietf-ipex#15]
I believe the statement

> Therefore, an Issuer commitment via a signature to any variant of ACDC (compact, full, etc) makes a cryptographic commitment to the top-level section fields shared by all variants of that ACDC because the value of a top level section field is either the SAD or the SAID of the SAD of the associated section.

no longer holds when we introduce nested partial disclosure.

Consider the case where an issuer signs a fully disclosed, nested, ACDC. During disclosure by the issuee/discloser, unless the discloser discloses all nested SAD, the uncompact/fully disclosed `a` SAID cannot be computed for verification.

To solve this, I can, by convention, always sign the most compact variant ACDC SAID during issuance, even if issuing a partially disclosable ACDC with all fields exposed for the issuee/discloser's use. This way any participant can validate, and the part of the ACDC transformation that goes in one direction only (blinding the partially disclosable SAD) kind of leads one to that result. The thing is, during issuance it would be nice to transfer the fully disclosed ACDC to reduce message quantity. But, the signature on the message wouldn't match the ACDC. Is that okay? I mean, I know I can write the code, but it probably isn't specified that way. Originally, I was planning on signing the compact version, sending that over to the recipient and then letting them query the issuer for all the SAD they need via `exn`/`bar` messages. Is this the correct approach? Or (by spec) can I sign the SAID of the compact variant and attach that signature to a fully disclosed ACDC?

**Comment by m00sey** [comment]
Potentially resolved by https://github.com/trustoverip/tswg-acdc-specification-archived/issues/78 @jasoncolburne ?

**Comment by jasoncolburne** [comment]
They are related, and it's not technically resolved because of acdc#78. I do think it belongs on an ACDC issue or discussion though, basically what I am saying here is that during exchanges and when referencing ACDCs externally, one should always use the most compact SAID since not all participants have access to levels of disclosure, which becomes particularly apparent when nesting partial disclosures.

I can close with this comment I believe.
